[package]
name = "bugi-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "25.0.2"
wasmparser = "0.219.1"
thiserror.workspace = true
anyhow.workspace = true
rmpv.workspace = true

bugi-core = { path = "../bugi-core" }
