[package]
name = "bugi-wasm-pdk"
version = "0.1.0"
edition = "2021"

[dependencies]
bugi-share = { path = "../bugi-share", features = [ "ser-rmp" ] }
bugi-wasm-pdk-macro.path = "../bugi-wasm-pdk-macro"

