name: Run Tests
on:
  push:
    branches: [main]
  pull_request:
jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy, cargo
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Run Tests
        run: |
          cargo test --workspace
      - name: Run Format Check
        run: |
          cargo fmt --all --check
