name: Run Tests
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Run Tests
        run: |
          nix develop -c cargo xtask test -f
  format:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run Format Check
        run: |
          nix develop -c cargo fmt --all --check
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run Lint
        run: |
          nix develop -c cargo clippy --workspace
